CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN 
    NEW.updated_at = CURRENT_TIMESTAMP
END
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER update_user_link 
BEFORE UPDATE ON links
FOR EACH ROW
EXECURE FUNCTION update_timestamp();